name: Check WB Prices

on:
  schedule:
    # Запуск каждые 2 часа
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка файлов
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установка библиотек
        run: |
          pip install requests

      - name: Выполнение проверки
        run: |
          python -u bot.py
